[MIG] account_journal_book_report: Migration to 15.0
ingadhoc/odoo-argentina-ee pull request #107
Opened 2022-05-12 14:38 UTC by JoelZilli

2022-05-12 14:38 UTC, roboadhoc commented
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ee/pull/107).

2022-05-12 19:07 UTC, nicomacr requested changes
@JoelZilli add the ACL's for the wizard model
Take this for eg:
![Screenshot (2)](https://user-images.githubusercontent.com/7657373/168150073-cfc0005f-ecb9-4d8d-b1c0-17e43892de2c.png)

2022-05-16 13:04 UTC, nicomacr approved these changes

2022-05-17 18:04 UTC, jjscarafia commented
@roboadhoc r+

2022-05-17 18:06 UTC, closed without merging