[IMP]l10n_ar_currency_update:onchange warning when currency name is c…
ingadhoc/odoo-argentina-ee pull request #115
Opened 2022-06-07 11:46 UTC by pablohmontenegro

…hanged.
Ticket: 51869

2022-06-07 11:46 UTC, roboadhoc commented
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ee/pull/115).

2022-06-07 14:22 UTC, zaoral requested changes

2022-06-07 14:22 UTC, zaoral commented on l10n_ar_currency_update/models/res_currency.py
> +        return {'warning': {'title': _('Warning'), 'message': 'Cambiar el nombre de la moneda puede repercutir tanto en el servicio de la sincronización automática de tasa de cambio como en el servic
Not sure why we have ths "No newline in end of file" error.
Maybe there is something can be fixed in the visual code configuration.

Please could you check it?

2022-06-07 14:22 UTC, zaoral commented on l10n_ar_currency_update/models/res_currency.py
> +        return {'warning': {'title': _('Warning'), 'message': 'Cambiar el nombre de la moneda puede repercutir tanto en el servicio de la sincronización automática de tasa de cambio como en el servic
Also add _() to the message
```suggestion
        return {'warning': {'title': _('Warning'), 'message': _('Cambiar el nombre de la moneda puede repercutir tanto en el servicio de la sincronización automática de tasa de cambio como en el servicio de la facturación electrónica.')}}
```

2022-06-07 14:22 UTC, zaoral commented on l10n_ar_currency_update/__manifest__.py
> +    'version': "15.0.1.1.0",
In this case, we are not updating the database ( model, views or data). So we do not need to increase the module version 
```suggestion
    'version': "15.0.1.0.0",
```

2022-06-08 15:00 UTC, zaoral approved these changes

2022-06-08 15:01 UTC, zaoral commented
@roboadhoc r+

2022-06-08 15:03 UTC, closed without merging