[IMP]l10n_ar_account_tax_settlement: retenciones y percepciones IVA txt
ingadhoc/odoo-argentina-ee pull request #153
Opened 2022-11-22 18:55 UTC by pablohmontenegro

Ticket: 54274

2022-11-22 18:55 UTC, roboadhoc commented
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ee/pull/153).

2022-12-16 18:08 UTC, ica-adhoc requested changes
@pablohmontenegro check the comments and prove that functions with the changes requested

2022-12-16 18:08 UTC, ica-adhoc commented on l10n_ar_account_tax_settlement/models/account_journal.py
> +                line.move_id.partner_id.ensure_vat()
ensure_vat() return l10n_ar_vat if this exists, call directly on add to content

2022-12-16 18:08 UTC, ica-adhoc commented on l10n_ar_account_tax_settlement/models/account_journal.py
> +                payment.partner_id.ensure_vat()
ensure_vat() return l10n_ar_vat if this exists, call directly on add to content

2022-12-16 18:08 UTC, ica-adhoc commented on l10n_ar_account_tax_settlement/models/account_journal.py
> +                # cuit agente (long 11)
the afip file specifies that the length is 13, was it a typing error?

2022-12-16 18:08 UTC, ica-adhoc commented on l10n_ar_account_tax_settlement/models/account_journal.py
> +                # cuit agente (long 11)
the afip file specifies that the length is 13, was it a typing error?

2022-12-16 18:29 UTC, pablohmontenegro commented on l10n_ar_account_tax_settlement/models/account_journal.py
> +                # cuit agente (long 11)
I resolve this bacause ica told me that is ok

2022-12-16 19:04 UTC, ica-adhoc approved these changes

2022-12-16 19:04 UTC, ica-adhoc commented
@roboadhoc r+

2022-12-16 19:44 UTC, closed without merging