[IMP] l10n_ar_edi_ux: boarding permission
ingadhoc/odoo-argentina-ee pull request #282
Opened 2023-11-02 19:33 UTC by pablohmontenegro

Task: 29241

2023-11-02 19:34 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/282).

2023-11-27 17:57 UTC, zaoral requested changes

2023-11-27 17:57 UTC, zaoral commented on l10n_ar_edi_ux/views/account_move_view.xml
> +                <field name='l10n_ar_boarding_permission_ids' widget="many2many_tags" attrs="{'invisible': [('l10n_ar_afip_ws', '!=', 'wsfex')]}"/>
please move field to Other Info tab, in the section named as AFIP.
Also check if you can create a permission from this view, this part is important please review it, if not we need to add extra options to make it work. The Create and Edit option should be shong, the Create option iteself should not be shown

2023-11-27 17:57 UTC, zaoral commented on l10n_ar_edi_ux/models/account_move.py
> +    l10n_ar_boarding_permission_ids = fields.Many2many('l10n_ar.boarding_permission', help="Solo se envía esta información si la factura es de exportación y el 'Concepto AFIP' es 'Products / Definiti
Add string "Permiso de Embarque" so this name is properly shown on the views

2023-11-27 17:57 UTC, zaoral commented on l10n_ar_edi_ux/models/l10n_ar_boarding_permission.py
> +    l10n_ar_boarding_permission_dst_country = fields.Many2one('res.country', string="País donde se aplica permiso de embarque")
not need to add  l10n_ar_boarding_ as a prefix to all fields.

The rule for the fields name is:
- if it is a new model, one that have l10n_ar prefix then the fields does not have to have l10n_ar preffix
- If we add a method to an existing model, a generic one (does not have any l10n_ar preffix in the model name= then we need to add the l10n_ar preffix.

Also:
1. the dst_country string should be the field help instead
2. make both fields required

```suggestion
    number = fields.Char(string="Permiso de embarque", required=True)
    dst_country = fields.Many2one('res.country', string="Pais Origen", help="País donde se aplica permiso de embarque", required=True)
```

2023-11-27 17:57 UTC, zaoral commented on l10n_ar_edi_ux/models/account_move.py
> +        res.update({'Permiso_existente': permiso_existente})
not need the else clause.
The original method already has this resolved.

Only the If is enough to add the permissions info if exist and needed 

```suggestion
        if int(self.l10n_latam_document_type_id.code) == 19 and int(self.l10n_ar_afip_concept) == 1:
            permisos = self._get_permissions()
            res.update({'Permisos': ArrayOfPermisions(permisos) if permisos else None})
            res.update({'Permiso_existente': "S" if permisos else "N"})
```

2023-11-27 17:57 UTC, zaoral commented on l10n_ar_edi_ux/models/l10n_ar_boarding_permission.py
> +    _rec_name = 'l10n_ar_boarding_permission_dst_country'
remove rec_name and instead define the display_name following this format "permisonum (Pais)" 
You can accomplish this by creating a name_get() and name_search() methods in this model.
This way we are able to see and search by contry and by permission number

2023-11-29 07:55 UTC, zaoral requested changes

2023-11-29 07:55 UTC, zaoral commented on l10n_ar_edi_ux/models/account_move.py
> +            response = client.service['FEXCheck_Permiso'](auth, request_data)
```suggestion
            response = client.service['FEXCheck_Permiso'](auth, Id_permiso=perm.number, Dst_merc=int(perm.dst_country.l10n_ar_afip_code))
```

2023-11-29 07:55 UTC, zaoral commented on l10n_ar_edi_ux/models/account_move.py
> +    l10n_ar_boarding_permission_ids = fields.Many2many('l10n_ar.boarding_permission', string="Permiso de Embarque", check_company=True, domain="[('company_id', 'in', [company_id, False])]", ondelete=
does we need  domain="[('company_id', 'in', [company_id, False])]",? 
I think we should not have any permission share withing companies.
Instead, please set company_id as required field in boarding model

2023-11-29 07:55 UTC, zaoral commented on l10n_ar_edi_ux/models/account_move.py
> +        res.update({'Permiso_existente': permiso_existente})
```suggestion
        if int(self.l10n_latam_document_type_id.code) == 19 and int(self.l10n_ar_afip_concept) == 1:
            ArrayOfPermisions = client.get_type('ns0:ArrayOfPermiso')
            permisos = self._get_permissions()
            permiso_existente = "S" if permisos else "N"
            res.update({'Permisos': ArrayOfPermisions(permisos) if permisos else None})
            res.update({'Permiso_existente': permiso_existente})
```

2023-11-29 07:55 UTC, zaoral commented on l10n_ar_edi_ux/models/l10n_ar_boarding_permission.py
> +    company_id = fields.Many2one('res.company', default=lambda self: self.env.company)
```suggestion
    company_id = fields.Many2one('res.company', required=True, default=lambda self: self.env.company)
```

2023-11-29 07:55 UTC, zaoral commented on l10n_ar_edi_ux/views/account_move_view.xml
> +                <field name='l10n_ar_boarding_permission_ids' widget="many2many_tags" attrs="{'invisible': [('l10n_ar_afip_ws', '!=', 'wsfex')]}" options="{'no_create_edit': False}"/>
```suggestion
                <field name='l10n_ar_boarding_permission_ids' widget="many2many_tags" attrs="{'invisible': [('l10n_ar_afip_ws', '!=', 'wsfex')]}" options="{'no_create': True, 'no_create_edit': False}"/>
```

2023-11-29 07:55 UTC, zaoral commented on l10n_ar_edi_ux/views/l10n_ar_boarding_permission_view.xml
> +                    <field name="dst_country"/>
add company field to view

2023-11-29 11:21 UTC, pablohmontenegro commented on l10n_ar_edi_ux/views/account_move_view.xml
> +                <field name='l10n_ar_boarding_permission_ids' widget="many2many_tags" attrs="{'invisible': [('l10n_ar_afip_ws', '!=', 'wsfex')]}" options="{'no_create_edit': False}"/>
Thanks! I already tried the change suggested but is not making the expected result, it shows both options (1: create, 2: create and edit)

2023-11-29 11:21 UTC, pablohmontenegro commented on l10n_ar_edi_ux/views/account_move_view.xml
> +                <field name='l10n_ar_boarding_permission_ids' widget="many2many_tags" attrs="{'invisible': [('l10n_ar_afip_ws', '!=', 'wsfex')]}" options="{'no_create_edit': False}"/>
@zaoral

2023-12-05 14:00 UTC, pablohmontenegro commented on l10n_ar_edi_ux/models/account_move.py
> +        res = []
acá llamar al botón

2023-12-15 15:21 UTC, zaoral commented
@roboadhoc r+

2023-12-15 17:21 UTC, zaoral commented
@roboadhoc override=ci/runbot-oba

we have a warning not related to this pr https://runbot.adhoc.com.ar/runbot/build/30421

2023-12-15 17:26 UTC, closed without merging