[ADD] l10n_ar_ux: Data on activities, taxes and concepts is create
ingadhoc/odoo-argentina-ee pull request #293
Opened 2023-12-14 00:44 UTC by mem-adhoc

Task: 28319

2023-12-14 00:44 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/293).

2024-01-26 18:26 UTC, zaoral requested changes

2024-01-26 18:26 UTC, zaoral commented on l10n_ar_edi_ux/models/res_partner.py
> +                if str(act.get('idActividad')) not in (self.actividades_padron.search([]).mapped('code')):
```suggestion
                if str(act.get('idActividad')) not in activity_codes:
```

2024-01-26 18:26 UTC, zaoral commented on l10n_ar_edi_ux/models/res_partner.py
> +            afip_activities = data_rg.get('actividad')
activity_codes = self.actividades_padron.search([]).mapped('code')

2024-01-26 18:26 UTC, zaoral commented on l10n_ar_edi_ux/models/res_partner.py
> +                if str(imp.get('idImpuesto')) not in (self.impuestos_padron.search([]).mapped('code')):
same of above

2024-01-30 22:42 UTC, zaoral approved these changes

2024-01-30 22:43 UTC, zaoral commented
@roboadhoc r+

2024-01-30 23:04 UTC, closed without merging