[IMP] l10n_ar_edi_ux: agregar funcionalidad de debitar cheques propios.
ingadhoc/odoo-argentina-ee pull request #297
Opened 2023-12-18 18:57 UTC by pablohmontenegro

Tarea: 34995
Lo hacemos acá y no en l10n_ar_ux porque no tenemos enterprise y usamos acá un metodo de account_accountant.

2023-12-18 18:58 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/297).

2023-12-21 15:00 UTC, jjscarafia requested changes

2023-12-21 15:00 UTC, jjscarafia commented on l10n_ar_edi_ux/wizards/account_check_action_wizard.py
> +        move_line_ids = [payment.line_ids.filtered(lambda x: not x.reconciled and x.account_type=='liability_current').id]
usaría el seek for lines porque puede tener otro tipo

2023-12-21 15:00 UTC, jjscarafia commented on l10n_ar_edi_ux/wizards/account_check_action_wizard.py
> +    def _get_outstanding_account(self, payment):
usaría algo más parecido a esto https://github.com/odoo/odoo/blob/16.0/addons/account/models/account_payment.py#L490

2023-12-21 15:00 UTC, jjscarafia commented on l10n_ar_edi_ux/__manifest__.py
> +        'wizards/account_check_action_wizard_view.xml',
agregar dependencia a account_accountant

2023-12-21 15:00 UTC, jjscarafia commented on l10n_ar_edi_ux/models/account_journal.py
> +    @api.onchange('check_add_debit_button')
check_debit_journal_id = fields.Many2one('account.journal', compute='_compute_check_debit_journal', store=True, readonly=False, domain="[('company_id', '=', company_id), ('type', '=', 'general')]", help="Debe seleccionar un diario de tipo 'Varios' donde se realizará el asiento del débito")

    @api.depends('check_add_debit_button')
    def _compute_check_debit_journal(self):
        """ En caso de que el campo 'Agregar botón de débito' (check_debit_journal_id) sea 'False' entonces debemos asegurarnos que el campo check_debit_journal_id esté vacío para evitar inconvenientes en caso de necesitar debitar un cheque. """
        for journal in self.filtered(lambda x: not x.check_add_debit_button):
            journal.check_debit_journal_id = False

2023-12-21 15:00 UTC, jjscarafia commented on l10n_ar_edi_ux/wizards/account_check_action_wizard.py
> +        move_line_ids = [payment.line_ids.filtered(lambda x: not x.reconciled and x.account_type=='liability_current').id]
_seek_for_lines (utilizando

liquidity_lines, counterpart_lines, writeoff_lines = payment._seek_for_lines()
move_line_ids = liquidity_lines.ids

2023-12-21 15:00 UTC, jjscarafia commented on l10n_ar_edi_ux/wizards/account_check_action_wizard.py
> +                            'balance': abs(payment.line_ids.filtered(lambda x: not x.reconciled and x.account_type=='liability_current').balance),
abs(sum(liquidity_lines.mapped('balance'))

2023-12-21 15:00 UTC, jjscarafia commented on l10n_ar_edi_ux/wizards/account_check_action_wizard.py
> +    def _get_outstanding_account(self, payment):
journal = payment.journal_id
journal_manual_payment_method = journal.outbound_payment_method_line_ids.filtered(lambda x: x.code=='manual')
outstanding_account = (journal_manual_payment_method.payment_account_id or journal.company_id.account_journal_payment_credit_account_id)
if not outstanding_account:
    raise UserError(_(
        "You can't create a new payment without an outstanding payments/receipts account set either on the company or the %s payment method in the %s journal.",
        self.payment_method_line_id.name, self.journal_id.display_name))

2023-12-21 18:41 UTC, jjscarafia commented
@roboadhoc r+

2023-12-21 18:45 UTC, closed without merging