[ADD] l10n_ar_edi_ux: mejora de rendimiento en actualización masiva de contactos
ingadhoc/odoo-argentina-ee pull request #358
Opened 2024-04-11 18:03 UTC by mem-adhoc

Task: 37730

2024-04-11 18:03 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/358).

2024-05-20 12:47 UTC, pablohmontenegro commented
Hello @mem-adhoc , please change l10n_ar_edi_ux manifest version. Thanks!

2024-05-20 19:05 UTC, pablohmontenegro requested changes

2024-05-20 19:05 UTC, pablohmontenegro commented on l10n_ar_edi_ux/models/res_partner.py
> +        default=False,
```suggestion
```

2024-05-20 19:05 UTC, pablohmontenegro commented on l10n_ar_edi_ux/models/res_partner.py
> +        string="Failed to update",
Not neccesary

2024-05-20 19:05 UTC, pablohmontenegro commented on l10n_ar_edi_ux/models/res_partner.py
> +        default=False,
Not neccesary

2024-05-20 19:05 UTC, pablohmontenegro commented on l10n_ar_edi_ux/views/res_partner_view.xml
> +                    <filter string="Failed to Update" name="failed_to_update" domain="[('failed_to_update', '=', True), ('country_code', '=', 'AR')]"/>
```suggestion
                    <filter string="Falló actualización AFIP" name="failed_to_update" domain="[('failed_to_update', '=', True), ('country_code', '=', 'AR')]"/>
```

2024-05-20 19:05 UTC, pablohmontenegro commented on l10n_ar_edi_ux/models/res_partner.py
> +        string="Failed to update",
```suggestion
        string="Falló actualización AFIP",
```

2024-05-20 19:20 UTC, zaoral requested changes

2024-05-20 19:20 UTC, zaoral commented on l10n_ar_edi_ux/wizards/res_partner_update_from_padron_wizard.py
> +            self.partner_id.failed_to_update = False
```suggestion
            self.partner_id.failed_to_update = False
            self.env.commit()
```

2024-05-20 19:20 UTC, zaoral commented on l10n_ar_edi_ux/wizards/res_partner_update_from_padron_wizard.py
> +            self.partner_id.failed_to_update = True
remove partner of the list

2024-05-20 19:20 UTC, zaoral commented on l10n_ar_edi_ux/wizards/res_partner_update_from_padron_wizard.py
> +            raise UserError('Fallo al actualizar el contacto: %s. Por favor quitelo de la lista e intente de nuevo' % self.partner_ids[0].name )
add translation _('')

2024-05-20 19:20 UTC, zaoral commented on l10n_ar_edi_ux/wizards/res_partner_update_from_padron_wizard.py
>          self.write(values)
add new field error on wizard.
set and clean up this field on earch partner iteration

if error then set this partner and show it as a yellow message on the wizard with the partner with error.
leave the failed_to_update = False.

2024-05-27 13:20 UTC, zaoral requested changes

2024-05-27 13:20 UTC, zaoral commented on l10n_ar_edi_ux/wizards/res_partner_update_from_padron_wizard.py
> +        default=''
do we need to set this default?

2024-05-27 13:20 UTC, zaoral commented on l10n_ar_edi_ux/wizards/res_partner_update_from_padron_wizard.py
> +                self.wizard_error = '<div class= "alert alert-warning" role="alert" style="margin-bottom:0px;" >' + res + '</div>'
1. Do not need res variable. add everything to the wizard_error directly
2. Not need to add "...  del contacto: %s' " because the name of the contact is already in the view.
3. If we have an error we can show we need to show it: Please add it to he wizard_error. Example (see bellow) you can add the error key to the message. 
![image](https://github.com/ingadhoc/odoo-argentina-ee/assets/7593953/0880013b-4334-490f-97f3-eb2034258f64)


Also, it will be good to show the error.
self.wizard_error  = str(exp)

If you can we can improve to show it different, show detail of the error hidden, use regex.

`self.wizard_error  = "firs part" + "<blockquote>%s</blockquote>"  str(exp)`

2024-05-27 13:20 UTC, zaoral commented on l10n_ar_edi_ux/wizards/res_partner_update_from_padron_wizard_view.xml
> +                    <field name="wizard_error" readonly="1" attrs="{'invisible': [('state', 'in', ('option',))]}"/>
wizard_error invisible is wizard_error  = False

2024-05-27 13:20 UTC, zaoral commented on l10n_ar_edi_ux/wizards/res_partner_update_from_padron_wizard.py
> +        except:
```suggestion
        except as exp:
```

2024-05-29 11:42 UTC, zaoral commented
@roboadhoc r+

2024-05-29 11:46 UTC, closed without merging