[IMP] Move bach payment edit to account_batch_payment_ux
ingadhoc/odoo-argentina-ee pull request #359
Opened 2024-04-11 18:22 UTC by cav-adhoc

2024-04-11 18:22 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/359).

2024-04-22 14:24 UTC, maq-adhoc requested changes
@cav-adhoc Te dejo tres pavadas para corregir

2024-04-22 14:24 UTC, maq-adhoc commented on account_batch_payment_ux/__manifest__.py
> +#    Copyright (C) 2015  ADHOC SA  (http://www.adhoc.com.ar)
Ya que estamos cambiemos la fecha :P

2024-04-22 14:24 UTC, maq-adhoc commented on account_batch_payment_ux/__manifest__.py
> +        'account_payment_group',
Estas dos dependencias no serian necesarias

2024-04-22 14:24 UTC, maq-adhoc commented on account_batch_payment_ux/__manifest__.py
> +        'account_reports',
No necesitamos account report

2024-04-24 14:12 UTC, rov-adhoc commented
@roboadhoc r+

2024-04-24 14:15 UTC, closed without merging