[FIX] l10n_ar_edi_ux: We consider whether the surname or first name data is empty
ingadhoc/odoo-argentina-ee pull request #363
Opened 2024-04-22 16:33 UTC by mem-adhoc

Task: 29136

2024-04-22 16:34 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/363).

2024-07-12 15:03 UTC, zaoral requested changes

2024-07-12 15:03 UTC, zaoral commented on l10n_ar_edi_ux/models/res_partner.py
> +        pdb.set_trace()
remove

2024-07-12 15:03 UTC, zaoral commented on l10n_ar_edi_ux/models/res_partner.py
> +                dictionary[val] = type_replace if not dictionary[val] else dictionary[val]
only check the element, and replace it with the type_replace that match if None

2024-07-12 15:03 UTC, zaoral commented on l10n_ar_edi_ux/models/res_partner.py
>          cat_mt = data_mt.get("categoriaMonotributo", {})
need to remove second line,         cat_mt = elf._clean_dict(data_rg.get("categoriaMonotributo"), type_replace={})

2024-07-12 15:03 UTC, zaoral commented on l10n_ar_edi_ux/models/res_partner.py
>          data_mt_actividades = data_mt.get("actividadMonotributista", []) or []
fusionar

2024-07-12 15:03 UTC, zaoral commented on l10n_ar_edi_ux/models/res_partner.py
> +        self._clean_dict(data_rg.get("impuesto"), type_replace=[])
esta repetido

2024-07-12 15:03 UTC, zaoral commented on l10n_ar_edi_ux/models/res_partner.py
>          domicilio = data.get("domicilioFiscal", {})
fusionar

2024-07-31 16:49 UTC, mem-adhoc commented on l10n_ar_edi_ux/models/res_partner.py
> +                dictionary[val] = type_replace if not dictionary[val] else dictionary[val]
Here we take the dictionary and really check if it has any None element, if it is None we replace it.

2024-07-31 16:51 UTC, mem-adhoc commented on l10n_ar_edi_ux/models/res_partner.py
>          domicilio = data.get("domicilioFiscal", {})
_clean_dict does not return anything, check if the dictionary had a None value and replace it. What do you mean by fusion?

2024-12-10 21:31 UTC, zaoral commented
@roboadhoc r+

2024-12-10 21:50 UTC, closed without merging