[FIX] l10n_ar_edi_ux: cambiar string del campo dst_country de "País Origen" a "País de destino de la mercadería"
ingadhoc/odoo-argentina-ee pull request #373
Opened 2024-04-30 14:47 UTC by pablohmontenegro

Ticket: 74144

2024-04-30 14:48 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/373).

2024-05-02 14:19 UTC, zaoral requested changes

2024-05-02 14:19 UTC, zaoral commented on l10n_ar_edi_ux/models/l10n_ar_boarding_permission.py
> +            )
delete this, leace only the sql constraint

2024-05-06 15:32 UTC, zaoral requested changes

2024-05-06 15:32 UTC, zaoral commented on l10n_ar_edi_ux/models/l10n_ar_boarding_permission.py
> +    dst_country = fields.Many2one('res.country', string="País de destino", help="País de destino de la mercadería", required=True)
delete line

2024-05-06 15:32 UTC, zaoral commented on l10n_ar_edi_ux/__manifest__.py
> +    'version': "16.0.1.8.0",
rebase, and change manifest version

2024-05-08 14:07 UTC, zaoral approved these changes

2024-05-08 14:08 UTC, zaoral commented
@roboadhoc r+

2024-05-08 14:11 UTC, closed without merging