[ADD] l10n_ar_account_tax_settlement: Nuevas disposiciones AGIP
ingadhoc/odoo-argentina-ee pull request #378
Opened 2024-05-06 18:48 UTC by mem-adhoc

Ticket: 74335

2024-05-06 18:48 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/378).

2024-05-08 13:32 UTC, pablohmontenegro commented on l10n_ar_account_tax_settlement/models/account_journal.py
> +                        break
content += '10' if or_inv.l10n_latam_document_type.code in [201, 206, 211] else '01'

2024-05-08 13:35 UTC, zaoral requested changes

2024-05-08 13:35 UTC, zaoral commented on l10n_ar_account_tax_settlement/README.rst
> +* AGIP: https://www.agip.gob.ar/agentes/agentes-de-recaudacion/ib-agentes-recaudacion/aplicativo-arciba/aclaraciones-sobre-las-adecuaciones-al-aplicativo-e-arciba- , https://www.agip.gob.ar/filemanag
```suggestion
* AGIP: https://www.agip.gob.ar/agentes/agentes-de-recaudacion/ib-agentes-recaudacion/aplicativo-arciba/aclaraciones-sobre-las-adecuaciones-al-aplicativo-e-arciba- y https://www.agip.gob.ar/agentes/agentes-de-recaudacion/ib-agentes-recaudacion/aplicativo-arciba/ag-rec-arciba-codigo-de-normas
   * NC https://www.agip.gob.ar/filemanager/source/Agentes/De Recaudacion/Ingresos brutos/NC.PDF  , 
   * RP https://www.agip.gob.ar/filemanager/source/Agentes/De Recaudacion/Ingresos brutos/RP.PDF 
```

2024-05-08 13:36 UTC, pablohmontenegro requested changes

2024-05-08 13:36 UTC, pablohmontenegro commented on l10n_ar_account_tax_settlement/README.rst
> +* AGIP: https://www.agip.gob.ar/agentes/agentes-de-recaudacion/ib-agentes-recaudacion/aplicativo-arciba/aclaraciones-sobre-las-adecuaciones-al-aplicativo-e-arciba- , https://www.agip.gob.ar/filemanag
aclarar en los links cuál es la versión, y fecha en la cual agregamos los links

2024-05-08 13:44 UTC, pablohmontenegro commented
@mem-adhoc adaptar el txt para retenciones/percepciones con la siguiente especificación:
https://www.agip.gob.ar/filemanager/source/Agentes/De%20Recaudacion/Ingresos%20brutos/RP.PDF

2024-05-14 18:55 UTC, zaoral requested changes

2024-05-14 18:55 UTC, zaoral commented on l10n_ar_account_tax_settlement/README.rst
> +* AGIP: 07-05-2024 https://www.agip.gob.ar/agentes/agentes-de-recaudacion/ib-agentes-recaudacion/aplicativo-arciba/aclaraciones-sobre-las-adecuaciones-al-aplicativo-e-arciba-
```suggestion
* AGIP: https://www.agip.gob.ar/agentes/agentes-de-recaudacion/ib-agentes-recaudacion/aplicativo-arciba/aclaraciones-sobre-las-adecuaciones-al-aplicativo-e-arciba-  (Version 3.0 aplicado el 07-05-2024) 
```

2024-05-14 18:55 UTC, zaoral commented on l10n_ar_account_tax_settlement/README.rst
> +   * RP 3.0 07-05-2024 https://www.agip.gob.ar/filemanager/source/Agentes/De%20Recaudacion/Ingresos%20brutos/RP.PDF
```suggestion
   * Notas de Credito 3.0 07-05-2024 https://www.agip.gob.ar/filemanager/source/Agentes/De%20Recaudacion/Ingresos%20brutos/NC.PDF
   * Retecion y Percepciones  3.0 07-05-2024 https://www.agip.gob.ar/filemanager/source/Agentes/De%20Recaudacion/Ingresos%20brutos/RP.PDF
   
```

2024-05-15 11:26 UTC, zaoral commented
@roboadhoc r+

2024-05-15 11:29 UTC, closed without merging