[FIX] l10n_ar_edi_ux: Permitimos pasar a borrador las facturas aceptadas en afip
ingadhoc/odoo-argentina-ee pull request #418
Opened 2024-07-01 15:43 UTC by mem-adhoc

Ticket: 76633
Task-related: 40643

2024-07-01 15:44 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/418).

2024-07-03 20:45 UTC, zaoral requested changes

2024-07-03 20:45 UTC, zaoral commented on l10n_ar_edi_ux/monkey_patches.py
> +    original_method = AccountMove._compute_show_reset_to_draft_button
este monkey patch no estaria funcionando.
1. en si no estaria llamanado el metodo de l10n_ar, pero esta sobre escribiendolo con lo que en teoria es lo que esta en account lo cual es un problema porque:
    1.  si lo de account cambia no lo sabemos y no lo tendremos dispinible. estas dejando una copia vieja no actualizada
    2. nos estamos saltandos todas las demas herencias que existen del metodo _compute_show_reset_to_draft_button por ejemplo las que estan en los modulos de stock y l10n_es. nosotros no queremos saltar, queremos que esas se ejecuten: solo queremos saltar el metodo de l10n_ar

2024-07-03 21:00 UTC, zaoral commented
superseded by https://github.com/ingadhoc/odoo-argentina-ee/pull/419

2024-07-03 21:01 UTC, closed without merging