[FW][ADD] l10n_ar_edi_ux: mejora de rendimiento en actualización masiva de contactos
ingadhoc/odoo-argentina-ee pull request #422
Opened 2024-07-12 15:22 UTC by fw-bot-adhoc

Task: 37730

Forward-Port-Of: ingadhoc/odoo-argentina-ee#410

2024-07-12 15:23 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/422).

2024-07-20 21:43 UTC, zaoral requested changes

2024-07-20 21:43 UTC, zaoral commented on l10n_ar_edi_ux/wizards/res_partner_update_from_padron_wizard_view.xml
> +=======
fix. this conflict will not make the odoo server even load

2024-07-20 21:43 UTC, zaoral commented on l10n_ar_edi_ux/models/res_partner.py
> +        tracking=True)
we are leaving to messages in the partner
- one the date the it fails
- another with the reason why it fails

I will like to have only one. please remove tracking=True here, and improve the partner-message_post to let the user know that the problem was realted to Fallo actualizacion AFIP

2024-07-20 21:43 UTC, zaoral commented on l10n_ar_edi_ux/wizards/res_partner_update_from_padron_wizard.py
> +                if resultado:
```suggestion
                
                if resultado := patron.search(str(exp)):
```

2024-07-25 16:20 UTC, zaoral requested changes

2024-07-25 16:20 UTC, zaoral commented on l10n_ar_edi_ux/wizards/res_partner_update_from_padron_wizard_view.xml
> +                    <field name="wizard_error" readonly="1" invisible = "not wizard_error"/>
```suggestion
                    <field name="wizard_error" readonly="1" invisible="not wizard_error"/>
```

2024-07-25 16:20 UTC, zaoral commented on l10n_ar_edi_ux/wizards/res_partner_update_from_padron_wizard.py
> +            partner.message_post(body=error)
```suggestion
            partner.message_post(body="Falló actualización AFIP: "+ error)
```

2024-08-09 14:42 UTC, zaoral commented
@mem-adhoc 
Maxi hacer el rebase de este pr para que lo mezclemos

2024-08-12 13:02 UTC, zaoral requested changes

2024-08-12 13:02 UTC, zaoral commented on l10n_ar_edi_ux/wizards/res_partner_update_from_padron_wizard.py
> +import re
Maxi, estas agregando campos, y modifcando vistas.
toca subir el version del manifest

tambien, seria bueno no se si ya esta, pero agregar esta info en el readme para que actualizemos cual es el comportamiento de la funcionalidad

2024-08-12 13:02 UTC, zaoral commented on l10n_ar_edi_ux/wizards/res_partner_update_from_padron_wizard.py
> +                partner.message_post(body="Falló actualización AFIP: "+ error)
crear un nuevo metodo que se llame algo como procesar_error donde coloquemos las lineas que procesando la info del error que estan repetidos

```suggestion
                self.process_error(exp)
```
```python
def process_error(self, exp):
       patron = re.compile(r"'error': \['(.*?)'\]")
                if resultado := patron.search(str(exp)):
                    error = resultado.group(1)
                else:
                    error = str(exp)
                partner.message_post(body="Falló actualización AFIP: "+ error)```

2024-08-12 13:02 UTC, zaoral commented on l10n_ar_edi_ux/wizards/res_partner_update_from_padron_wizard.py
> +            partner.message_post(body="Falló actualización AFIP: "+ error)
```suggestion
                self.process_error(exp)
```

2024-08-20 21:24 UTC, zaoral commented
@roboadhoc r+

2024-08-20 21:44 UTC, closed without merging