[REF] l10n_ar_account_tax_settlement: sircar refactor para poder cump…
ingadhoc/odoo-argentina-ee pull request #445
Opened 2024-09-09 15:42 UTC by pablohmontenegro

…limentar personalización de tarea 38394

Tarea: 38394

2024-09-09 15:43 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/445).

2024-10-07 12:49 UTC, zaoral requested changes

2024-10-07 12:49 UTC, zaoral commented on l10n_ar_account_tax_settlement/models/account_journal.py
> +            if not float(alicuot_line) and not alicuot_line:
```suggestion
            if not type(alicuot_line, float) and not alicuot_line:
```

2024-10-07 12:49 UTC, zaoral commented on l10n_ar_account_tax_settlement/models/account_journal.py
> +                alicuot_line.alicuota_retencion if not float(alicuot_line) else alicuot_line, 6, 2, '.'))
do not cast

2024-10-07 12:49 UTC, zaoral commented on l10n_ar_account_tax_settlement/models/account_journal.py
> +            if not float(alicuot_line) and not alicuot_line.regimen_retencion:
do not cast

2024-10-07 12:49 UTC, zaoral commented on l10n_ar_account_tax_settlement/models/account_journal.py
> +            content.append(alicuot_line.regimen_retencion if not float(alicuot_line) else line.tax_line_id.codigo_regimen)
do not cast

2024-10-28 17:09 UTC, zaoral commented on l10n_ar_txt_mendoza/models/account_journal.py
> +import re
from odoo.addons.l10n_ar_account_tax_settlement.models.account_journal import nombre_function

2024-10-28 17:10 UTC, pablohmontenegro commented on l10n_ar_txt_mendoza/__manifest__.py
> +    'application': True,
```suggestion
    'application': False,
```

2024-10-29 12:11 UTC, zaoral requested changes

2024-10-29 12:11 UTC, zaoral commented on l10n_ar_txt_mendoza/__init__.py
> +from . import wizard
```suggestion
from . import wizards
```

2024-10-29 12:11 UTC, zaoral commented on l10n_ar_txt_mendoza/__manifest__.py
> +    'name': 'TXT Mendoza',
I did not find anything more short :( 

rename to l10n_ar_txt_mendoza to (next options):

 a. l10n_ar_account_tax_settlement_mendoza
 b. l10n_ar_tax_settlement_mza
 b. l10n_ar_tax_mendoza

```suggestion
    'name': 'Tax settlement Mendoza',
```

2024-10-29 12:11 UTC, zaoral commented on l10n_ar_txt_mendoza/models/account_journal.py
> +def format_amount(amount, padding=15, decimals=2, sep=""):
Simplify code by importing the methods, do not repeat them here (format_amount, get_pos_and_number, get_line_tax_base)

from odoo.addons.l10n_ar_account_tax_settlement.models.account_journal import nombre_function1, nombre_function2, nombre_function3

2024-10-29 12:11 UTC, zaoral commented on l10n_ar_txt_mendoza/models/account_move.py
> +        domain="[('id', 'in', actividades_padron)]"
can use partner_id.actividades_padron? if not work, then defined in the view? and delete field actividades_padron

2024-10-29 12:11 UTC, zaoral commented on l10n_ar_txt_mendoza/models/account_payment.py
> +    alicuota_mendoza = fields.Float(store=True, readonly=True)
1. if regular field remove (store=True) not needed.
2. why not related  to  payment_group_id.alicuota_mendoza? if related field then check if the store=True is needed? why?

2024-10-29 12:28 UTC, pablohmontenegro commented on l10n_ar_txt_mendoza/__init__.py
> +from . import wizard
Thanks @zaoral odoo uses https://github.com/odoo/odoo/blob/16.0/addons/account/__init__.py#L7 "from . import wizard", it is necessary to make the change?

2024-10-29 13:00 UTC, pablohmontenegro commented on l10n_ar_txt_mendoza/models/account_move.py
> +        domain="[('id', 'in', actividades_padron)]"
@zaoral I think actividades_padron related field is necessary because with this change https://gist.github.com/pablohmontenegro/234275bb2b2376ee09a5fa5f4aa3dbd6 I receive this bug with traceback when I want to add activities in the vendor bill form view in the field activities_mendoza_ids https://gist.github.com/pablohmontenegro/a16fa403b4f790b338579e38a8bf3e10 (previosly I did -u to the module)

2024-10-29 13:02 UTC, pablohmontenegro commented on l10n_ar_txt_mendoza/models/account_journal.py
> +def format_amount(amount, padding=15, decimals=2, sep=""):
@zaoral I am not using this method anymore

2024-10-29 13:11 UTC, pablohmontenegro commented on l10n_ar_txt_mendoza/models/account_payment.py
> +    alicuota_mendoza = fields.Float(store=True, readonly=True)
@zaoral 
1. ok, i changed it
2. beucase if I change to related field then alicuota_mendoza will be set on all the withholdings, not only withholdings for mendoza

2024-10-29 15:32 UTC, zaoral reviewed
Only apply IMPORTANT key
The other ones can be applied after merge, not to urgent

2024-10-29 15:32 UTC, zaoral commented on l10n_ar_account_tax_settlement_mendoza/models/account_journal.py
> +from odoo.exceptions import ValidationError, RedirectWarning
remove  ValidationError not used in this fle

2024-10-29 15:32 UTC, zaoral commented on l10n_ar_account_tax_settlement_mendoza/models/account_journal.py
> +# from odoo.tools import DEFAULT_SERVER_DATE_FORMAT
remove commented imports

2024-10-29 15:32 UTC, zaoral commented on l10n_ar_account_tax_settlement_mendoza/models/account_journal.py
> +import re
also not used, please remove import re

2024-10-29 15:32 UTC, zaoral commented on l10n_ar_account_tax_settlement_mendoza/models/account_move.py
> +from odoo import models, fields, api
remove api not used import

2024-10-29 15:32 UTC, zaoral commented on l10n_ar_account_tax_settlement_mendoza/models/account_payment.py
> +from odoo import models, fields, api
remove api not used import

2024-10-29 15:32 UTC, zaoral commented on l10n_ar_account_tax_settlement_mendoza/models/account_payment_group.py
> +from odoo import models, api, fields, _
remove not used api import

2024-10-29 15:32 UTC, zaoral commented on l10n_ar_account_tax_settlement_mendoza/models/account_payment_group.py
> +            raise ValidationError('No puede calcular retenciones automáticas de aplicadas de Mendoza si no seleccionó una factura para pagar')
IMPORTANT: 

Estaria saltando siempre que este el impuesto activo, para todos los casos, deberia ser solo para el caso de que el payment group tenga lineas de mendoza

2024-10-29 15:32 UTC, zaoral commented on l10n_ar_account_tax_settlement_mendoza/models/account_payment_group.py
> +        else:
else no seria necesario

2024-10-29 15:32 UTC, zaoral commented on l10n_ar_account_tax_settlement_mendoza/models/account_tax.py
> +from odoo import models, fields, api, _
not used fields, api, and _ remove imports. same UserError  and relativedelta

2024-10-29 15:32 UTC, zaoral commented on l10n_ar_account_tax_settlement_mendoza/models/account_tax.py
> +        """ La alícuota para el archivo txt de mendoza que se genera desde el método iibb_aplicado_sircar_files_values no se obtiene del partner sino que se obtiene del payment, y el código de régime
120 max

2024-10-29 15:32 UTC, zaoral commented on l10n_ar_account_tax_settlement_mendoza/models/account_tax.py
> +            aliquot = self.env['res.partner.arba_alicuot'].new({'alicuota_retencion': line.payment_id.alicuota_mendoza * 100, 'partner_id': partner, 'regimen_retencion': line.payment_id.tax_withholdi
```suggestion
          return self.env['res.partner.arba_alicuot'].new({'alicuota_retencion': line.payment_id.alicuota_mendoza * 100, 'partner_id': partner, 'regimen_retencion': line.payment_id.tax_withholding_id.codigo_regimen})
```

2024-10-29 15:32 UTC, zaoral commented on l10n_ar_account_tax_settlement_mendoza/models/account_tax.py
> +        return aliquot
```suggestion
        return super().get_partner_alicuot(partner, date, line)
```

2024-10-29 15:32 UTC, zaoral commented on l10n_ar_account_tax_settlement_mendoza/models/res_company.py
> +    def process_csv_file(self, partner_vat, activity_codes):
nombre muy generico, cambiar por otro para evitar problemas

2024-10-29 15:32 UTC, zaoral commented on l10n_ar_account_tax_settlement_mendoza/models/res_company.py
> +            csv_data = StringIO(csv_content.decode('utf-8'))
```suggestion
            csv_content = base64.b64decode(self.riesgo_fiscal_csv_file, 'utf-8')
            csv_data = StringIO(csv_content)
```

2024-10-29 15:32 UTC, zaoral commented on l10n_ar_account_tax_settlement_mendoza/models/res_company.py
> +            raise UserError('Debe subir el archivo de riesgo fiscal en la sección de ajustes de contabilidad para calcular la retención automática de Mendoza.')
```suggestion
        raise UserError('Debe subir el archivo de riesgo fiscal en la sección de ajustes de contabilidad para calcular la retención automática de Mendoza.')
```

2024-10-29 15:32 UTC, zaoral commented on l10n_ar_account_tax_settlement_mendoza/wizards/res_config_settings.py
> +        string="Última Modificación"
quitar string

2024-10-29 15:32 UTC, zaoral commented on l10n_ar_account_tax_settlement_mendoza/wizard/res_config_settings.py
> +        string="Última Modificación"
quitar, ya lo tienes en la vista

2024-10-29 15:32 UTC, zaoral commented on l10n_ar_account_tax_settlement/models/account_journal.py
> +                line.partner_id, line.date, line)
IMPORTANT: get_partner_alicuot define in original method

2024-10-29 15:32 UTC, zaoral commented on l10n_ar_account_tax_settlement_mendoza/models/account_tax.py
> +            aliquot = super().get_partner_alicuot(partner, date)
IMPORTANT: 
            aliquot = super().get_partner_alicuot(partner, date ,line=line)

2024-10-29 15:46 UTC, zaoral commented on l10n_ar_account_tax_settlement_mendoza/__manifest__.py
> +    'version': "16.0.1.0.0",
Agregar readme explicandoque hace el modulo.porque esta por seprado, caso especial, que se sube a un aplicativo distinto, y los pasos a configurar posterior a instalar (importar archivo afip activity, archivo riesgo fiscal)

2024-10-29 20:43 UTC, zaoral commented
@roboadhoc r+

2024-10-29 20:45 UTC, closed without merging