[MIG] l10n_ar_currency_update: Migration to 18.0
ingadhoc/odoo-argentina-ee pull request #457
Opened 2024-10-10 17:43 UTC by pablohmontenegro

2024-10-10 17:43 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/457).

2024-11-21 20:25 UTC, zaoral requested changes

2024-11-21 20:25 UTC, zaoral commented on l10n_ar_currency_update/README.rst
> +This will add AFIP Web Service as your currency provider (official argentinian provider). It is neccesary to have afip certificate updated.
```suggestion
This will add AFIP Web Service as your currency provider (official argentinian provider). It is neccesary to have set on the company afip valid certificate.
```

2024-11-21 20:25 UTC, zaoral commented on l10n_ar_currency_update/README.rst
>  By default the automatic rate updates are inactive, you can active them by company
Mas abajo dodne dice "tipo de cambio DIVISA"  agregar "de Venta"

2024-11-21 20:25 UTC, zaoral commented on l10n_ar_currency_update/models/res_company.py
quitar import _
quitar en general todos los imports que no estemos usando

2024-11-21 20:25 UTC, zaoral commented on l10n_ar_currency_update/models/res_company.py
quitar         default='afip',
 ya resuelto en el campo compute del modulo original

2024-11-21 20:25 UTC, zaoral commented on l10n_ar_currency_update/models/res_company.py
> +            company = self.env.company if self.env.company.sudo().l10n_ar_afip_ws_crt_id else self.env['res.company'].search(
eliminar el metodo create del res_company, ya estaria solucionado el flujo con el _compute_currency_provider.
Si te prece bien pablito, tocaria eliminarlo, y probar de crear una nueva compania argentina y ver que este deteado el valor currency provider bien

2024-11-21 20:25 UTC, zaoral commented on l10n_ar_currency_update/models/res_company.py
> +                [('l10n_ar_afip_ws_crt_id', '!=', False), ('l10n_ar_afip_ws_crt_id.date_end', '>', today)], limit=1)
elimnar _compute_currency_provider. ya se resuelve en el metodo original, cada vez que cambian el pais, cambia el valor

2024-11-21 20:25 UTC, zaoral commented on l10n_ar_currency_update/models/res_company.py
> +            company = self.env.company if self.env.company.sudo().l10n_ar_afip_ws_crt_id else self.env['res.company'].search(
Que tome el certificado de la companía actual si esta es valido, y sino el primero certificado valido que consiga.

```python
            valid_certificate = self.env['certificate.certificate'].search(
                [('active', '=', True), ('date_end', '>', today), ("country_code", "=!", "AR")]) 
            company = self.env.company if self.env.company.l10n_ar_afip_ws_crt_id in valid_certificate \
                        else valid_certificate[0].company_id 
```

2024-11-21 20:25 UTC, zaoral commented on l10n_ar_currency_update/models/res_company.py
>                  return False
Simplificar el metodo _generate_currency_rates ejemplo:
```python
    def _generate_currency_rates(self, parsed_data):
        """ Apply surcharge for on afip rates
        
        * condicion 1: si ya existe la tasa para el dia de una moneda en especifco usamos dicha tasa pre
                       existente y no usamos las que nos dio AFIP
        * condicion 2: Si tenemos definido una tasa de recargo o una percepcion definido en la compañia
                       necesitamos volver a calcula la información de la tasa AFIP mas esos montos extras
        """
        currency_rate = self.env['res.currency.rate']
        currency_object = self.env['res.currency']
        for company in self.filtered(lambda x: x.currency_provider == 'afip' and (x.rate_surcharge or x.rate_perc)):
            for currency, (rate, date_rate) in parsed_data.items():
                already_existing_rate = currency_rate.search([
                    ('currency_id', '=', currency_object.search([('name', '=', currency)]).id),
                    ('name', '=', date_rate),
                    ('company_id', '=', company.id)])
                if not already_existing_rate and rate and rate != 1.0:
                    rate = 1.0 / rate
                    rate = rate * (1.0 + (company.rate_perc or 0.0))
                    rate += (company.rate_surcharge or 0.0)
                    rate = 1.0 / rate
                    parsed_data[currency] = (rate, date_rate)

        super()._generate_currency_rates(parsed_data)
```

2024-11-21 20:25 UTC, zaoral commented on l10n_ar_currency_update/__manifest__.py
>          'data/res_company_data.xml',
me parece que este arhcivo se puede eliminar, ya que funciona como compute al instalar el modulo (verficiar) 
```suggestion
```

2024-11-26 15:34 UTC, pablohmontenegro commented on l10n_ar_currency_update/__manifest__.py
>          'data/res_company_data.xml',
Por lo que probé entiendo que es necesario para que al instalar se corra el método _compute_currency_provider y se setee en las compañías argentinas el valor 'afip' en el campo "currency_provider"

2024-11-26 15:35 UTC, pablohmontenegro commented on l10n_ar_currency_update/models/res_company.py
> +                [('l10n_ar_afip_ws_crt_id', '!=', False), ('l10n_ar_afip_ws_crt_id.date_end', '>', today)], limit=1)
El método original está igual en 17 y en 16, entiendo que es necesario el método de acuerdo a las pruebas que hice porque sino no se cambia el valor

2024-12-05 18:25 UTC, zaoral commented
forzamos ya que hay un error externo en runbot no relacionado
https://runbot.adhoc.com.ar/runbot/batch/71543/build/97599

@roboadhoc override=ci/runbot-oba

@roboadhoc r+

2024-12-05 18:26 UTC, zaoral commented
@roboadhoc r+

2024-12-05 18:28 UTC, roboadhoc commented
I'm sorry, @zaoral: this PR is already reviewed, reviewing it again is useless.

2024-12-05 18:29 UTC, closed without merging