[MIG] l10n_ar_account_reports: Migration to 18.0
ingadhoc/odoo-argentina-ee pull request #458
Opened 2024-10-10 18:46 UTC by mem-adhoc

2024-10-10 18:46 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/458).

2024-10-29 19:08 UTC, rov-adhoc approved these changes

2024-10-31 13:29 UTC, maq-adhoc requested changes

2024-10-31 13:29 UTC, maq-adhoc commented on l10n_ar_account_reports/wizards/checks_to_date_report.py
> +                        LEFT JOIN account_payment AS acp ON lc.payment_id = acp.id
en ves de LEFT JOIN account_payment podria ser  JOIN account_payment no hay cheques si payment. lo mismo para account_payment_method

2024-10-31 13:29 UTC, maq-adhoc commented on l10n_ar_account_reports/wizards/checks_to_date_report.py
> +                        WHERE apm.code = 'check_printing' AND ap_move.date <= '%s'
check_printing no existe mas ahora es own_checks

2024-10-31 13:29 UTC, maq-adhoc commented on l10n_ar_account_reports/wizards/checks_to_date_report.py
>                          WHERE apm.code = 'check_printing' AND aml.id <> aml_2.id
Idem anterior

2024-10-31 13:29 UTC, maq-adhoc commented on l10n_ar_account_reports/wizards/checks_to_date_report.py
> +            WHERE t2.operation_date IS NULL OR (t2.operation_code != 'out_third_party_checks')
No estoy seguro si sacar paired_code no cambia el result.
podes ver el codigo  issue_state para obtener esta info?

2025-02-01 00:25 UTC, zaoral commented
supersed by https://github.com/ingadhoc/odoo-argentina-ee/pull/544

2025-02-01 00:25 UTC, closed without merging