[IMP] l10n_ar_txt_tucuman: new module
ingadhoc/odoo-argentina-ee pull request #461
Opened 2024-10-17 18:20 UTC by pablohmontenegro

Tarea: 38200

2024-10-17 18:21 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/461).

2024-11-11 13:05 UTC, pablohmontenegro commented on l10n_ar_txt_tucuman/README.rst
> +=============================
corregir

2024-11-11 13:05 UTC, pablohmontenegro commented on l10n_ar_txt_tucuman/__manifest__.py
> +    'images': [
quitar

2024-11-11 13:05 UTC, pablohmontenegro commented on l10n_ar_txt_tucuman/__manifest__.py
> +    'test': [
quitar

2024-11-11 13:05 UTC, pablohmontenegro commented on l10n_ar_txt_tucuman/models/account_journal.py
> +            raise ValidationError(f"Algunos comprobantes rectificativos no contienen información de que comprobante original están revirtiendo: %s" % (", ".join(nc_without_reversed_entry_id.mapped('m
```suggestion
            raise UserError(_("Algunos comprobantes rectificativos no contienen información de que comprobante original están revirtiendo: %s") % (", ".join(nc_without_reversed_entry_id.mapped('move_id.name'))))
```

2024-11-11 13:05 UTC, pablohmontenegro commented on l10n_ar_txt_tucuman/models/account_journal.py
> +            raise ValidationError(f"Algunos comprobantes no contienen información acerca de la calle/ciudad/provincia/cod postal del contacto: %s" % (", ".join(moves_without_street_city_state.mapped(
```suggestion
            raise UserError(_("Algunos comprobantes no contienen información acerca de la calle/ciudad/provincia/cod postal del contacto: %s") % (", ".join(moves_without_street_city_state.mapped('move_id.name'))))
```

2024-11-11 13:05 UTC, pablohmontenegro commented on l10n_ar_txt_tucuman/models/account_journal.py
> +from odoo import models, fields
```suggestion
from odoo import models, fields, _
```

2024-11-11 13:05 UTC, pablohmontenegro commented on l10n_ar_txt_tucuman/models/account_journal.py
> +from odoo.exceptions import ValidationError
```suggestion
from odoo.exceptions import UserError
```

2024-11-11 13:05 UTC, pablohmontenegro commented on l10n_ar_txt_tucuman/models/account_journal.py
> +            # 99 para retenciones por el ejemplo que pasó en el archivo adjunto el cliente en la tareas
```suggestion
            # 99 para retenciones por el ejemplo que pasó en el archivo adjunto el cliente en la tarea
```

2024-11-11 13:05 UTC, pablohmontenegro commented on l10n_ar_txt_tucuman/models/account_journal.py
> +
Agragar validación para que no tenga punto de venta de 5 dígitos

2024-11-11 13:05 UTC, pablohmontenegro commented on l10n_ar_txt_tucuman/models/account_journal.py
> +            content_datos += '%06.3f' % line.tax_line_id.get_partner_alicuot(line.partner_id, line.date).alicuota_percepcion
que tome alicuota_retencion para retenciones

2024-11-12 14:46 UTC, zaoral requested changes

2024-11-12 14:46 UTC, zaoral commented on l10n_ar_txt_tucuman/models/account_journal.py
> +        if line.move_type == 'out_refund':
1. agregar doscstring.
2. recibir lineas (todas las que son necesarias para crear el archivo)

```python

    def _iibb_tucuman_ncfact_txt_file(self, lines):
       """ Devuelve contenido del archivo NCFACT.TXT Txt Tucuman
       """
        content_ncfact = ''
        for line in lines.filtered(lamba x: x.move_type == 'out_refund'):
             ...

```

2024-11-12 14:46 UTC, zaoral commented on l10n_ar_txt_tucuman/models/account_journal.py
> +        return ''
always return at the end of the method
```suggestion
    return content_ncfact
```

2024-11-12 14:46 UTC, zaoral commented on l10n_ar_txt_tucuman/models/account_journal.py
> +            content_ncfact += '\r\n'
this should end be per line, or per file?

2024-11-12 14:46 UTC, zaoral commented on l10n_ar_txt_tucuman/models/account_journal.py
> +    def _iibb_tucuman_retper_txt_file(self, line):
process lines, return only content of the file. str

2024-11-12 14:46 UTC, zaoral commented on l10n_ar_txt_tucuman/models/account_journal.py
> +        return content_datos if content_datos else ''
you already initialize the content_ncfact = ''
```suggestion
        return content_datos
```

2024-11-12 14:46 UTC, zaoral commented on l10n_ar_txt_tucuman/models/account_journal.py
> +    def _iibb_tucuman_datos_txt_file(self, line, percepciones):
receive lines instad of lines, do not pass perceptions.
in the iteration of each line create a temporal varialbe is_perception

```python
for line in lines:
    is_perception = line.l10n_latam_document_type_id.internal_type == 'invoice'
    ....
```

2024-11-12 14:46 UTC, zaoral commented on l10n_ar_txt_tucuman/models/account_journal.py
> +            'txt_content': content_ncfact,
```suggestion
        # VALIDACIONES
        self._iibb_tucuman_validations(move_lines)

        # ELABORACIÓN DE ARCHIVOS TXT
        lines = move_lines.sorted(key=lambda r: (r.date, r.id))
        return [{
                'txt_filename': 'DATOS.txt',
                'txt_content': self._iibb_tucuman_datos_txt_file(lines),
            }, {
                'txt_filename': 'RETPER.txt',
                'txt_content': self._iibb_tucuman_retper_txt_file(lines),
            }, {
                'txt_filename': 'NCFACT.TXT',
                'txt_content': self._iibb_tucuman_ncfact_txt_file(lines),
```

2024-11-12 14:46 UTC, zaoral commented on l10n_ar_txt_tucuman/models/account_journal.py
> +    def _iibb_tucuman_validations(self, move_lines):
Validation should be only validation, not need to return perceptions

2024-11-12 17:09 UTC, pablohmontenegro commented on l10n_ar_txt_tucuman/models/account_journal.py
> +            content_ncfact += '\r\n'
yes

2024-11-12 19:39 UTC, zaoral requested changes

2024-11-12 19:39 UTC, zaoral commented on l10n_ar_txt_tucuman/models/account_journal.py
> +        percepciones = self._iibb_tucuman_validations(move_lines)
```suggestion
        self._iibb_tucuman_validations(move_lines)
```

2024-11-12 19:39 UTC, zaoral commented on l10n_ar_txt_tucuman/models/account_journal.py
> +        content_datos, content_retper, content_ncfact = '', '', ''
```suggestion
```

2024-11-12 19:51 UTC, zaoral approved these changes

2024-11-12 19:52 UTC, zaoral commented
@roboadhoc r+

2024-11-12 20:10 UTC, closed without merging