[MIG] account_journal_book_report: Migration to 18.0
ingadhoc/odoo-argentina-ee pull request #478
Opened 2024-11-04 20:00 UTC by pablohmontenegro

2024-11-04 20:01 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/478).

2024-11-21 14:15 UTC, zaoral requested changes
TODO

- [x] tenemos un solo archivo en models con dos modelos, separar para que tengamos un achivo por modelo
- [ ] recordar eliminar los imports que no se estan usando
- [ ] renombrar account_views a account_journal_views
- [x] quitarla el mensje en vista journal string=Journal Book Report y colocaria esto directo como nombre de campo
- [x] quitar         string='Company',
- [x] quitar         string='Journals',
- [ ] max 120 lineas
- [ ] rename method check_report a action_check_report
- [ ] move rla info de la carpeta reporte, pasarlo al mismo archivo de la vista del mismo modelo

2024-11-21 14:15 UTC, zaoral commented on account_journal_book_report/wizard/account_journal_book_report.py
remove line

2024-11-21 18:47 UTC, pablohmontenegro commented
@zaoral @mem-adhoc cómo están? aplique los cambios sugeridos.

2024-11-22 13:51 UTC, zaoral requested changes

2024-11-22 13:51 UTC, zaoral commented on account_journal_book_report/wizard/account_journal_book_report_views.xml
>                  </group>
Campo journal_ids tiene algo raro, esta definido como required True en modelo, pero en vista esta escondido y tiene un required=0.

Yo le quitaria el required=0 y veria como funciona. De ultima pedir a maru cuales son los comportamientos que debe tener.

Tampoco estoy segura si realmente necesitamos agregarlo en la vista, capaz ya no es necesario? directamente quitarlo?

```diff
- <field name="journal_ids" invisible="1" required="0"/>
+ <field name="journal_ids" invisible="1"/>
````

2024-11-22 13:51 UTC, zaoral commented on account_journal_book_report/__manifest__.py
>          'security/ir.model.access.csv',
puedes eliminar la carpeta report, y tambien su init interno, no usamos ninguno.
recordar en el modulo/init quitar el import report

2024-11-22 20:51 UTC, pablohmontenegro commented on account_journal_book_report/wizard/account_journal_book_report_views.xml
>                  </group>
Lo probé y me parece que se puede sacar. (ya lo saqué)

2024-11-25 12:37 UTC, zaoral approved these changes
@roboadhoc r+

2024-11-25 12:40 UTC, closed without merging