[MIG] l10n_ar_edi_ux: Migration to 18.0
ingadhoc/odoo-argentina-ee pull request #480
Opened 2024-11-09 15:05 UTC by pablohmontenegro

2024-11-09 15:05 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/480).

2024-12-03 11:31 UTC, zaoral requested changes

2024-12-03 11:31 UTC, zaoral commented on l10n_ar_edi_ux/__manifest__.py
> +        'account_check_printing'
@pablohmontenegro 
why this dependency?

In version 17 we have the l10n_latam_check module that depends on account_check_printing, And in version 18 now  l10n_latam_check does not depends on  account_check_printing, they are two separate modulos with different logic. If you need to change something related to checks should be done by depending and extending l10n_latam_check instead of  account_check_printing.

We will wait for @MarianaLuzTorres response maybe we can move the button to a nother new l10n_latam_check_ux module.

2024-12-03 18:07 UTC, zaoral commented on l10n_ar_edi_ux/__manifest__.py
> +        'account_check_printing'
@pablohmontenegro 
Pablito dejar como esta
ya lo hable con contabilidad,
ellos estan haciendo un pr a odoo 17 donde van a separar tema del repote y cheques a otro modulo
asi que dejemos como esta ahora, y luego le va a llegar el fw (el pr lo esta trabajando rov)

2024-12-16 17:30 UTC, jjscarafia commented
@roboadhoc r+

2024-12-16 17:48 UTC, closed without merging