[FIX] l10n_ar_account_tax_settlement: Error en ValidationError
ingadhoc/odoo-argentina-ee pull request #489
Opened 2024-11-19 20:09 UTC by cmanuelalvarez11

Originalmente el fragmento de la función era
`    if not alicuot_line:
                    raise ValidationError(
                    'No hay alicuota configurada en el partner '
                    '"%s" (id: %s)') % (
                        line.partner_id.name, line.partner_id.id)`
Nótese los params de cadena fuera de la función lo que detonaba el siguiente error
ValueError: <class 'TypeError'>: "unsupported operand type(s) for %: 'ValidationError' and 'tuple'" while evaluating

Solucionado:
raise ValidationError(
                        'No hay alicuota configurada en el partner "{}" (id: {})'.format(
                            line.partner_id.name, line.partner_id.id)

2024-11-19 20:09 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/489).

2024-11-20 12:13 UTC, jobiols commented
hola @zaoral como estas,
te dejo este mensaje a ver si podes darle curso es un error muy pavo.
Gracias.

2024-11-20 14:17 UTC, zaoral requested changes

2024-11-20 14:17 UTC, zaoral commented on l10n_ar_account_tax_settlement/models/account_journal.py
> +    )
```suggestion
                    'No hay alicuota configurada en el partner '
                    '"%s" (id: %s)' % (
                        line.partner_id.name, line.partner_id.id))
    )
```

2024-11-20 14:20 UTC, zaoral commented
Hola @jobiols 
Como estas?

Muchas gracias por reportar el error y por el PR
Te envié una sugerencia para que lo puedas revisar y ver de adaptar en el PR

Cambiando solo el orden de donde es cerrado el paréntesis soluciona el problema
Nos parece mas sustentable así ya que modificamos menos código, y mantenemos el mismo formato de los mensajes de error que construimos, (usando % como en otros lugares en lugar de la función format())

Una vez que tengas el cambio me avisas y hacemos el merge.
Saludos!

2024-11-20 17:31 UTC, cmanuelalvarez11 commented
hola @zaoral se actualizó el code para que mantengan la uniformidad de su código, quedamos atentos... muchas gracias

2024-11-20 19:02 UTC, zaoral approved these changes

2024-11-20 21:07 UTC, zaoral requested changes
Hola @cmanuelalvarez11
Gracias por los cambios.

Di approve pero luego me di cuenta que dio error en runbot,
Quedo un parentesis de mas en la linea 1358
Podrias eliminarlo

Una vez realizado el cambio me avisas y lo vuelvo a revisar
Saludos!

2024-11-20 21:07 UTC, zaoral commented on l10n_ar_account_tax_settlement/models/account_journal.py
> +    )
```suggestion
```

2024-11-20 21:48 UTC, cmanuelalvarez11 commented
Actualizado @zaoral

2024-11-21 11:38 UTC, maq-adhoc approved these changes

2024-11-21 11:52 UTC, zaoral approved these changes

2024-11-21 11:52 UTC, zaoral commented
Gracias por los cambios!
@roboadhoc r+

2024-11-21 11:56 UTC, zaoral commented
Hola @cmanuelalvarez11 

Intente mezclarlo, pero me salto error y no me dejo.
Esto porque quedaron 3 commits en lugar de uno (deberia ser solo uno).
Por si suma, para poder aprobarla debemos asegurar que sea un solo commit, o ver de forzar la mezcla con varios con un comando especial si realmente sean necesarios llevar varios commits por separado

Este caso me parece que un solo commit bastaria.
Podrias revisarlo y hacer un squash de los commits y luego un force push?
Si se te complica avisame y ayudo con este ultimo pendiente.

Saludos!

2024-11-21 12:16 UTC, roboadhoc commented
@cmanuelalvarez11 @zaoral because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

2024-11-21 15:10 UTC, cmanuelalvarez11 commented
hola @zaoral ... quedó hecho el commit y el force push, quedo atento

2024-11-21 15:28 UTC, zaoral commented
@roboadhoc r+

2024-11-21 15:32 UTC, closed without merging