[IMP] account_accountant_ux: Remove inconsistent code
ingadhoc/odoo-argentina-ee pull request #491
Opened 2024-11-21 16:41 UTC by rov-adhoc

2024-11-21 16:41 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/491).

2024-11-25 14:50 UTC, jjscarafia requested changes

2024-11-25 14:50 UTC, jjscarafia commented on accountant_ux/README.rst
> +Installation
ya que pedí lo de abajo acá agregaría un salto del línea

2024-11-25 14:50 UTC, jjscarafia commented on accountant_ux/data/accountant_data.xml
> +    <data noupdate="1">
toda esta parte se borraría ya que queda en account_accountant_ux

2024-11-28 15:19 UTC, merged