[FIX] l10n_ar_currency_update: l10n_ar_last_currency_sync_date when ar rates are not created
ingadhoc/odoo-argentina-ee pull request #505
Opened 2024-12-16 13:03 UTC by pablohmontenegro

Ticket: 84697

2024-12-16 13:04 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/505).

2024-12-18 11:59 UTC, zaoral requested changes

2024-12-18 11:59 UTC, zaoral commented on l10n_ar_currency_update/models/res_company.py
> +                    raise UserError("afip_date (+1) %s, rate_date (today), %s" % (afip_date, rate_date))
Returned Afip rate is not today's rate (%s vs %s)
Example;
"""Returned Afip rate is not today's rate (Sabado, 2024-12-14 vs Lunes, 2024-12-16) ·

2024-12-18 19:44 UTC, zaoral commented
@roboadhoc r+

2024-12-18 20:04 UTC, closed without merging