[IMP] l10n_ar_account_tax_settlement: sicore aplicado iva percepciones
ingadhoc/odoo-argentina-ee pull request #82
Opened 2022-01-18 20:24 UTC by pablohmontenegro

Ticket: 47086.Generates the txt file for sicore IVA applied insights

2022-01-18 20:24 UTC, roboadhoc commented
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ee/pull/82).

2022-02-03 19:00 UTC, zaoral requested changes
Hi @pablohmontenegro 
Hope you are doing well.
Leave you some suggestions and questions about this PR,
we can check it together

Best Regards

2022-02-03 19:00 UTC, zaoral commented on l10n_ar_account_tax_settlement/models/account_journal.py
> +                # content += TODO escribir...ej, factura, nc, etc
remove comment
```suggestion
```

2022-02-03 19:00 UTC, zaoral commented on l10n_ar_account_tax_settlement/models/account_journal.py
> +                content += '%02d' % int(move.l10n_latam_document_type_id.code)
Not sure that this is Ok. the document type code does not match with the Codigo Comprobante. View video in ticket
```suggestion
                if move.l10n_latam_document_type_id.code in [1, 6, 11, 51...]:
                     ccode = '01'
                elif move.l10n_latam_document_type_id.code in [4, 9, 15, 54...]:
                     ccode = '02'
                elif... other cases....
                content += '%02d' % ccode
```

2022-02-03 19:00 UTC, zaoral commented on l10n_ar_account_tax_settlement/models/account_journal.py
> +                amount_tot = abs(payment.payment_group_id.payments_amount)
why you applied abs() here? I ask because the preivuos version that do not have retention was without the abs
```suggestion
                amount_tot = abs(payment.payment_group_id.payments_amount)
```

2022-02-03 19:00 UTC, zaoral commented on l10n_ar_account_tax_settlement/models/account_journal.py
> -                    self.env.ref('l10n_ar.tax_group_percepcion_ganancias')):
what happend in the case of l10n_ar.tax_group_percepcion_ganancias?

2022-02-03 19:00 UTC, zaoral commented on l10n_ar_account_tax_settlement/models/account_journal.py
> +                base_amount = payment.withholding_base_amount
I think here should be payment.withholdable_base_amount?
```suggestion
                base_amount = payment.withholdable_base_amount
```

2022-02-03 19:00 UTC, zaoral commented on l10n_ar_account_tax_settlement/models/account_journal.py
> +            content += '%014.2f' % abs(line.balance)
when do report the importe de percepcion? should not be here?

2022-02-03 19:00 UTC, zaoral commented on l10n_ar_account_tax_settlement/models/account_tax.py
> +from odoo import api, models, fields
remove api import, not used
```suggestion
from odoo import models, fields
```

2022-02-04 20:33 UTC, zaoral commented on l10n_ar_account_tax_settlement/models/account_journal.py
> +            content += '%014.2f' % abs(line.balance)
Please add a comment to the right indication that this field is also used as Improte de Percepcion

2022-02-08 23:43 UTC, zaoral approved these changes

2022-02-08 23:44 UTC, zaoral commented
@roboadhoc r+

2022-02-09 00:05 UTC, closed without merging