[FIX] l10n_ar_account_reports: select partner not "None"
ingadhoc/odoo-argentina-ee pull request #88
Opened 2022-01-27 15:00 UTC by pablohmontenegro

Ticket: 48567. Select partners if they are not "None".

2022-01-27 15:00 UTC, roboadhoc commented
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ee/pull/88).

2022-01-31 18:07 UTC, zaoral requested changes

2022-01-31 18:07 UTC, zaoral commented on l10n_ar_account_reports/models/account_partner_ledger.py
> +        if partner is not None and partner.l10n_latam_identification_type_id.name and partner.vat:
```suggestion
        if partner  and partner.l10n_latam_identification_type_id.name and partner.vat:
```

2022-01-31 18:21 UTC, zaoral approved these changes

2022-01-31 18:22 UTC, zaoral commented
@roboadhoc r+

2022-01-31 18:34 UTC, closed without merging